###################################################
# Base images, with common environment, for sibcoin-docker
###################################################

FROM jkilbride/node-npm-alpine:6

RUN apk update && \
    apk add --no-cache curl \
    python \
    make \
    git \
    g++ \
    bash \
    openssl=1.0.2k-r0 \
    nodejs \
    tar \
    nano \
    mc \
    findutils \
    libzmq3-dev \
    build-essential

#RUN groupadd sibcore
#RUN useradd sibcore -m -s /bin/bash -g sibcore
#USER sibcore
#WORKDIR /home/sibcore