version: "2"

services:
  sibcore:
    build:
      context: ./composes-services/sibcore
    environment:
      - NETWORK=livenet
    ports:
      - 3001:3001
      - 1945:1945
    volumes:
      - "./apps/bitcore:/home/sibcore/.nvm/versions/node/v4.8.4/lib/node_modules/bitcore/"

