###################################################
#
###################################################
FROM sib-base:latest
USER sibcore
RUN /home/sibcore/.nvm/versions/node/v4.8.4/bin/sibcore -V

--rm


#RUN /home/sibcore/.nvm/versions/node/v4.8.4/bin/sibcore create /home/sibcore/node



#USER root
#ADD install.sh ${HOME}/install.sh
#RUN chown sibcore:sibcore ${HOME}/install.sh
#RUN chmod +x ${HOME}/install.sh
#
#USER sibcore
#ENTRYPOINT ${HOME}/install.sh






#ENTRYPOINT ${HOME}/install.sh

#RUN ${HOME}/install.sh | bash
#RUN chown sibcore:sibcore ${HOME}/node

#RUN chown sibcore:sibcore ${HOME}/install.sh

#USER sibcore
#WORKDIR ${HOME}

#RUN /home/sibcore/.nvm/versions/node/v4.8.4/bin/sibcore create node

#VOLUME ${HOME}/node

# Create livenet fullnode
###################################################
# WORKDIR ${HOME}
# RUN . ${NVM_DIR}/nvm.sh &&\
#     sibcore create nodelivenet
#
# ADD ./networks/livenet/bitcore-node.json ${HOME}/nodelivenet/bitcore-node.json
# ADD ./networks/livenet/package.json ${HOME}/nodelivenet/package.json
# ADD ./networks/livenet/bitcoin.conf ${HOME}/data/bitcoin.conf
# ADD ./networks/livenet/start.sh ${HOME}/start.sh
