###################################################
#
###################################################
FROM node:8

# Create livenet fullnode
###################################################
# WORKDIR ${HOME}
# RUN . ${NVM_DIR}/nvm.sh &&\
#     sibcore create nodelivenet
#
# ADD ./networks/livenet/bitcore-node.json ${HOME}/nodelivenet/bitcore-node.json
# ADD ./networks/livenet/package.json ${HOME}/nodelivenet/package.json
# ADD ./networks/livenet/bitcoin.conf ${HOME}/data/bitcoin.conf
# ADD ./networks/livenet/start.sh ${HOME}/start.sh
