###################################################
# Copay
###################################################
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get -y install g++ make python git curl tar nano mc

RUN groupadd sibcore
RUN useradd sibcore -m -s /bin/bash -g sibcore

ENV HOME "/home/sibcore"
ENV NODE_VERSION "6.7.0"
ENV NVM_DIR "/home/sibcore/.nvm"

USER sibcore

WORKDIR ${HOME}

RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash

RUN . ${NVM_DIR}/nvm.sh &&\
    nvm install $NODE_VERSION &&\
    nvm alias default $NODE_VERSION

ENV PATH ${PATH}":/home/sibcore/.nvm/versions/node/v${NODE_VERSION}/bin"

RUN npm install -g grunt-cli
RUN npm install -g cordova
RUN npm install -g node-sass
RUN npm install -g coffee-script
RUN npm install -g bower
RUN npm update --no-optional && npm install -g ionic

WORKDIR ${HOME}/copay
VOLUME ${HOME}/copay

ADD start.sh ${HOME}/start.sh

EXPOSE 8100

CMD bash ${HOME}/start.sh