###################################################
# Copay
###################################################
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get -y install g++ make python git curl tar nano mc build-essential

RUN groupadd sibcore
RUN useradd sibcore -m -s /bin/bash -g sibcore

ENV HOME "/home/sibcore"
ENV NODE_VERSION "6.7.0"
ENV NVM_DIR "/home/sibcore/.nvm"

RUN git clone https://github.com/Werdffelynir/copay.git ${HOME}/copay &&\
    chown sibcore:sibcore -R ${HOME}/copay &&\
    chmod 755 -R  ${HOME}/copay

USER sibcore

RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash

WORKDIR ${HOME}/copay

RUN . ${NVM_DIR}/nvm.sh &&\
    nvm install $NODE_VERSION &&\
    nvm alias default $NODE_VERSION &&\
    npm install -g bower grunt-cli ionic &&\
    npm run apply:copay


ENV PATH ${PATH}":${HOME}/.nvm/versions/node/v${NODE_VERSION}/bin"

#RUN npm install -g grunt-cli
#RUN npm install -g cordova
#RUN npm install -g node-sass
#RUN npm install -g coffee-script
#RUN npm install -g bower
#RUN npm install -g fsevents
#RUN npm install -g ionic

# npm update --no-optional &&



#RUN


#RUN npm install && \
#    bower install --production --force --allow-root --config.interactive=false && \
#    grunt

EXPOSE 8100

#VOLUME ${HOME}/copay

ADD start.sh ${HOME}/start.sh
CMD bash ${HOME}/start.sh