###################################################
# Copay
###################################################
FROM ubuntu:16.04

RUN apt-get update
RUN apt-get -y install g++ make python git curl tar nano mc build-essential

RUN groupadd sibcore
RUN useradd sibcore -m -s /bin/bash -g sibcore

ENV HOME "/home/sibcore"
ENV NODE_VERSION "6.7.0"
ENV NVM_DIR "/home/sibcore/.nvm"

RUN git clone https://github.com/Werdffelynir/copay.git ${HOME}/copay &&\
    chown sibcore:sibcore -R ${HOME}/copay &&\
    chmod 755 -R  ${HOME}/copay

USER sibcore

RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash

WORKDIR ${HOME}/copay

RUN . ${NVM_DIR}/nvm.sh &&\
    nvm install $NODE_VERSION &&\
    nvm alias default $NODE_VERSION &&\
    npm install -g bower grunt-cli ionic@1

ENV PATH ${PATH}":${HOME}/.nvm/versions/node/v${NODE_VERSION}/bin"

RUN npm install -g cordova@4.2.0
RUN npm run apply:copay

EXPOSE 8100

VOLUME ${HOME}/copay

RUN ls -la ${HOME}
RUN mkdir ${HOME}/.ionic && touch ${HOME}/.ionic/daemon.log && chown sibcore:sibcore -R ${HOME}/.ionic
#USER root
#ADD ./.ionic/daemon.log ${HOME}/.ionic/daemon.log
#RUN  chown sibcore:sibcore -R ${HOME}/.ionic/daemon.log && chmod 777 -R ${HOME}/.ionic/daemon.log
#USER sibcore

ADD start.sh ${HOME}/start.sh
CMD bash ${HOME}/start.sh

















####################################################
## Copay
####################################################
#FROM agileek/ionic-framework
#
#RUN apt-get update
#RUN apt-get -y install g++ make python git curl tar nano mc build-essential
#
#RUN groupadd sibcore
#RUN useradd sibcore -m -s /bin/bash -g sibcore
#
#ENV HOME "/home/sibcore"
#ENV NODE_VERSION "6.7.0"
#ENV NVM_DIR "/home/sibcore/.nvm"
#
#RUN git clone https://github.com/Werdffelynir/copay.git ${HOME}/copay &&\
#    chown sibcore:sibcore -R ${HOME}/copay &&\
#    chmod 755 -R  ${HOME}/copay
#
#USER sibcore
#
#RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
#
#WORKDIR ${HOME}/copay
#
#RUN . ${NVM_DIR}/nvm.sh &&\
#    nvm install $NODE_VERSION &&\
#    nvm alias default $NODE_VERSION &&\
#    npm install -g bower grunt-cli &&\
#    npm run apply:copay
#
#
#ENV PATH ${PATH}":${HOME}/.nvm/versions/node/v${NODE_VERSION}/bin"
#
#EXPOSE 8100
#
#VOLUME ${HOME}/copay
#
#ADD start.sh ${HOME}/start.sh
#CMD bash ${HOME}/start.sh