###################################################
#
###################################################
FROM sib-base:latest

USER sibcore
WORKDIR ${HOME}

ENV PATH "/home/werd/.nvm/versions/node/v4.8.4/bin:/usr/local/bin"
RUN /home/sibcore/.nvm/versions/node/v4.8.4/bin/sibcore create node
#VOLUME ${HOME}/node

#

#CMD ["npm", "-v"]

#CMD ["npm", "install", "git+https://git@github.com/Werdffelynir/bitcore.git", "-g"]
